name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.17
    - name: Install dependencies
      run: dotnet restore ${{github.workspace}}/WebApplication1/WebApplication1/WebApplication1.csproj
    - name: Build
      run: dotnet build ${{github.workspace}}/ModernSourceControl/WebApplication1/WebApplication1/WebApplication1.csproj --no-restore
    - name: Test
      run: dotnet test ${{github.workspace}}/ModernSourceControl/WebApplication1/WebApplication1/WebApplication1.csproj --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ${{github.workspace}}/WebApplication1/WebApplication1/WebApplication1.csproj -c Release -o dotnetcorewebapp
      
